In [1]:
#### COLAB ONLY CELL
from google.colab import drive
drive.mount('/content/gdrive')
# drive.mount('/content/gdrive',force_remount=True)
%cd /content/gdrive/MyDrive/COMEXT
!pip install -r ./comext-graph-analysis/requirements.txt

Mounted at /content/gdrive
/content/gdrive/MyDrive/COMEXT

In [2]:
import pandas as pd

In [ ]:
for y in range(2001,2022):
    print("\n",y)
    df1 = pd.read_csv(f"./data-samples/full/full{y}01.dat")#,dtype="str",encoding="utf-8",encoding_errors='replace',on_bad_lines='skip',lineterminator='\n')
    df1.to_parquet(f"./data-samples/movements/full{y}01.parquet")
    df = df1[df1.PRODUCT_NC == "TOTAL"]
    del df1
    for m in range(2,13):
        print(str(m)+" ",end="")
        df2 = pd.read_csv(f"./data-samples/full/full{y*100+m}.dat")#,dtype="str",encoding="utf-8",encoding_errors='replace',on_bad_lines='skip',lineterminator='\n')
        df2.to_parquet(f"./data-samples/movements/full{y*100+m}.parquet")
        df2 = df2[df2.PRODUCT_NC == "TOTAL"]
        df = pd.concat([df,df2])
        del df2
    df.reset_index(drop=True).to_parquet(f"./data-samples/full/Month/full{y}_total.parquet")
    del df

In [ ]:
import chardet
with open(f"./data-samples/full/full{y*100+m}.dat", 'rb') as rawdata:
    result = chardet.detect(rawdata.read(100000000))
result

{'confidence': 1.0, 'encoding': 'ascii', 'language': ''}

In [ ]:
pd.read_csv(f"./data-samples/full/full200208.dat",dtype="str",encoding="utf-8",encoding_errors='replace',on_bad_lines='skip')

        DECLARANT DECLARANT_ISO  ... QUANTITY_IN_KG SUP_QUANTITY
0             001            FR  ...              0            1
1             001            FR  ...           1800            6
2             001            FR  ...          12500           25
3             001            FR  ...           4400            9
4             001            FR  ...           2800           55
...           ...           ...  ...            ...          ...
1441823                    NaN  ...            NaN          NaN
1441824         1           NaN  ...              0          NaN
1441825      289C         1��S0  ...            NaN          NaN
1441826       008            DK  ...            NaN          NaN
1441827    �00208           862  ...            NaN          NaN

[1441828 rows x 19 columns]

In [7]:
corrupted = []
for y in [2002,2014,2015]:
    print(y)
    for m in [8,3]:
        print(f"{y*100+m}")
        try:
            df3 = pd.read_csv(f"./data-samples/full/full{y*100+m}.dat")
            del df3
        except:
            print(f"full{y*100+m}.dat")
            corrupted.append(f"full{y*100+m}.dat")
            # del df3
print(corrupted)

2002
200208
200203
2014
201408
201403
2015
201508
201503
[]